package PriSpark.TPCDS

import org.apache.spark.sql.SparkSession
import org.apache.spark.sql.catalyst.ScalaReflection
import org.apache.spark.sql.types.StructType

//varchar => String
//char => String
//date => String
//time => String
//integer => Long
//decimal => Double

class TPCDSSchemaProvider_Qriginal(spark: SparkSession, inputDir: String) {

  val time1 = System.currentTimeMillis()

  val store_sales = spark.read.option("delimiter", "|").schema(ScalaReflection.schemaFor[StoreSales].dataType.asInstanceOf[StructType]).csv(inputDir + "/store_sales.dat")
  val store_returns = spark.read.option("delimiter", "|").schema(ScalaReflection.schemaFor[StoreReturns].dataType.asInstanceOf[StructType]).csv(inputDir + "/store_returns.dat")
  val catalog_sales = spark.read.option("delimiter", "|").schema(ScalaReflection.schemaFor[CatalogSales].dataType.asInstanceOf[StructType]).csv(inputDir + "/catalog_sales.dat")
  val catalog_returns = spark.read.option("delimiter", "|").schema(ScalaReflection.schemaFor[CatalogReturns].dataType.asInstanceOf[StructType]).csv(inputDir + "/catalog_returns.dat")
  val web_sales = spark.read.option("delimiter", "|").schema(ScalaReflection.schemaFor[WebSales].dataType.asInstanceOf[StructType]).csv(inputDir + "/web_sales.dat")
  val web_returns = spark.read.option("delimiter", "|").schema(ScalaReflection.schemaFor[WebReturns].dataType.asInstanceOf[StructType]).csv(inputDir + "/web_returns.dat")
  val inventory = spark.read.option("delimiter", "|").schema(ScalaReflection.schemaFor[Inventory].dataType.asInstanceOf[StructType]).csv(inputDir + "/inventory.dat")
  val store = spark.read.option("delimiter", "|").schema(ScalaReflection.schemaFor[Store].dataType.asInstanceOf[StructType]).csv(inputDir + "/store.dat")
  val call_center = spark.read.option("delimiter", "|").schema(ScalaReflection.schemaFor[CallCenter].dataType.asInstanceOf[StructType]).csv(inputDir + "/call_center.dat")
  val catalog_page = spark.read.option("delimiter", "|").schema(ScalaReflection.schemaFor[CatalogPage].dataType.asInstanceOf[StructType]).csv(inputDir + "/catalog_page.dat")
  val web_site = spark.read.option("delimiter", "|").schema(ScalaReflection.schemaFor[WebSite].dataType.asInstanceOf[StructType]).csv(inputDir + "/web_site.dat")
  val web_page = spark.read.option("delimiter", "|").schema(ScalaReflection.schemaFor[WebPage].dataType.asInstanceOf[StructType]).csv(inputDir + "/web_page.dat")
  val warehouse = spark.read.option("delimiter", "|").schema(ScalaReflection.schemaFor[Warehouse].dataType.asInstanceOf[StructType]).csv(inputDir + "/warehouse.dat")
  val customer = spark.read.option("delimiter", "|").schema(ScalaReflection.schemaFor[Customer].dataType.asInstanceOf[StructType]).csv(inputDir + "/customer.dat")
  val customer_address = spark.read.option("delimiter", "|").schema(ScalaReflection.schemaFor[CustomerAddress].dataType.asInstanceOf[StructType]).csv(inputDir + "/customer_address.dat")
  val customer_demographics = spark.read.option("delimiter", "|").schema(ScalaReflection.schemaFor[CustomerDemographics].dataType.asInstanceOf[StructType]).csv(inputDir + "/customer_demographics.dat")
  val date_dim = spark.read.option("delimiter", "|").schema(ScalaReflection.schemaFor[DateDim].dataType.asInstanceOf[StructType]).csv(inputDir + "/date_dim.dat")
  val household_demographics = spark.read.option("delimiter", "|").schema(ScalaReflection.schemaFor[HouseholdDemographics].dataType.asInstanceOf[StructType]).csv(inputDir + "/household_demographics.dat")
  val item = spark.read.option("delimiter", "|").schema(ScalaReflection.schemaFor[Item].dataType.asInstanceOf[StructType]).csv(inputDir + "/item.dat")
  val income_band = spark.read.option("delimiter", "|").schema(ScalaReflection.schemaFor[IncomeBand].dataType.asInstanceOf[StructType]).csv(inputDir + "/income_band.dat")
  val promotion = spark.read.option("delimiter", "|").schema(ScalaReflection.schemaFor[Promotion].dataType.asInstanceOf[StructType]).csv(inputDir + "/promotion.dat")
  val reason = spark.read.option("delimiter", "|").schema(ScalaReflection.schemaFor[Reason].dataType.asInstanceOf[StructType]).csv(inputDir + "/reason.dat")
  val ship_mode = spark.read.option("delimiter", "|").schema(ScalaReflection.schemaFor[ShipMode].dataType.asInstanceOf[StructType]).csv(inputDir + "/ship_mode.dat")
  val time_dim = spark.read.option("delimiter", "|").schema(ScalaReflection.schemaFor[TimeDim].dataType.asInstanceOf[StructType]).csv(inputDir + "/time_dim.dat")
  val dbgen_version = spark.read.option("delimiter", "|").schema(ScalaReflection.schemaFor[DbgenVersion].dataType.asInstanceOf[StructType]).csv(inputDir + "/dbgen_version.dat")

  store_sales.write.mode("overwrite").saveAsTable("store_sales")
  store_returns.write.mode("overwrite").saveAsTable("store_returns")
  catalog_sales.write.mode("overwrite").saveAsTable("catalog_sales")
  catalog_returns.write.mode("overwrite").saveAsTable("catalog_returns")
  web_sales.write.mode("overwrite").saveAsTable("web_sales")
  web_returns.write.mode("overwrite").saveAsTable("web_returns")
  inventory.write.mode("overwrite").saveAsTable("inventory")
  store.write.mode("overwrite").saveAsTable("store")
  call_center.write.mode("overwrite").saveAsTable("call_center")
  catalog_page.write.mode("overwrite").saveAsTable("catalog_page")
  web_site.write.mode("overwrite").saveAsTable("web_site")
  web_page.write.mode("overwrite").saveAsTable("web_page")
  warehouse.write.mode("overwrite").saveAsTable("warehouse")
  customer.write.mode("overwrite").saveAsTable("customer")
  customer_address.write.mode("overwrite").saveAsTable("customer_address")
  customer_demographics.write.mode("overwrite").saveAsTable("customer_demographics")
  date_dim.write.mode("overwrite").saveAsTable("date_dim")
  household_demographics.write.mode("overwrite").saveAsTable("household_demographics")
  item.write.mode("overwrite").saveAsTable("item")
  income_band.write.mode("overwrite").saveAsTable("income_band")
  promotion.write.mode("overwrite").saveAsTable("promotion")
  reason.write.mode("overwrite").saveAsTable("reason")
  ship_mode.write.mode("overwrite").saveAsTable("ship_mode")
  time_dim.write.mode("overwrite").saveAsTable("time_dim")
  dbgen_version.write.mode("overwrite").saveAsTable("dbgen_version")

  val time2 = System.currentTimeMillis()

  //  println(spark.catalog.currentDatabase)
  //  spark.catalog.listDatabases().show(false)

  val tables = Array("store_sales","store_returns","catalog_sales","catalog_returns","web_sales","web_returns","inventory","store","call_center","catalog_page","web_site","web_page","warehouse","customer","customer_address","customer_demographics","date_dim","household_demographics","item","income_band","promotion","reason","ship_mode","time_dim","dbgen_version")
  var num:Long = 0
  for (t <- tables){
    num = num + spark.table(t).count()
  }

  val time3 = System.currentTimeMillis()


  
  //  spark.sql("ANALYZE TABLE dbgen_version COMPUTE STATISTICS")
  //  spark.sql("ANALYZE TABLE dbgen_version COMPUTE STATISTICS FOR COLUMNS dv_version")
  //  spark.sql("ANALYZE TABLE dbgen_version COMPUTE STATISTICS FOR COLUMNS dv_create_date")
  //  spark.sql("ANALYZE TABLE dbgen_version COMPUTE STATISTICS FOR COLUMNS dv_create_time")
  //  spark.sql("ANALYZE TABLE dbgen_version COMPUTE STATISTICS FOR COLUMNS dv_cmdline_args")

  spark.sql("ANALYZE TABLE customer_address COMPUTE STATISTICS")
  spark.sql("ANALYZE TABLE customer_address COMPUTE STATISTICS FOR COLUMNS ca_address_sk")
  //  spark.sql("ANALYZE TABLE customer_address COMPUTE STATISTICS FOR COLUMNS ca_address_id")
  //  spark.sql("ANALYZE TABLE customer_address COMPUTE STATISTICS FOR COLUMNS ca_street_number")
  //  spark.sql("ANALYZE TABLE customer_address COMPUTE STATISTICS FOR COLUMNS ca_street_name")
  //  spark.sql("ANALYZE TABLE customer_address COMPUTE STATISTICS FOR COLUMNS ca_street_type")
  //  spark.sql("ANALYZE TABLE customer_address COMPUTE STATISTICS FOR COLUMNS ca_suite_number")
  //  spark.sql("ANALYZE TABLE customer_address COMPUTE STATISTICS FOR COLUMNS ca_city")
  //  spark.sql("ANALYZE TABLE customer_address COMPUTE STATISTICS FOR COLUMNS ca_county")
  //  spark.sql("ANALYZE TABLE customer_address COMPUTE STATISTICS FOR COLUMNS ca_state")
  //  spark.sql("ANALYZE TABLE customer_address COMPUTE STATISTICS FOR COLUMNS ca_zip")
  //  spark.sql("ANALYZE TABLE customer_address COMPUTE STATISTICS FOR COLUMNS ca_country")
  //  spark.sql("ANALYZE TABLE customer_address COMPUTE STATISTICS FOR COLUMNS ca_gmt_offset")
  //  spark.sql("ANALYZE TABLE customer_address COMPUTE STATISTICS FOR COLUMNS ca_location_type")

  spark.sql("ANALYZE TABLE customer_demographics COMPUTE STATISTICS")
  spark.sql("ANALYZE TABLE customer_demographics COMPUTE STATISTICS FOR COLUMNS cd_demo_sk")
  //  spark.sql("ANALYZE TABLE customer_demographics COMPUTE STATISTICS FOR COLUMNS cd_gender")
  //  spark.sql("ANALYZE TABLE customer_demographics COMPUTE STATISTICS FOR COLUMNS cd_marital_status")
  //  spark.sql("ANALYZE TABLE customer_demographics COMPUTE STATISTICS FOR COLUMNS cd_education_status")
  //  spark.sql("ANALYZE TABLE customer_demographics COMPUTE STATISTICS FOR COLUMNS cd_purchase_estimate")
  //  spark.sql("ANALYZE TABLE customer_demographics COMPUTE STATISTICS FOR COLUMNS cd_credit_rating")
  //  spark.sql("ANALYZE TABLE customer_demographics COMPUTE STATISTICS FOR COLUMNS cd_dep_count")
  //  spark.sql("ANALYZE TABLE customer_demographics COMPUTE STATISTICS FOR COLUMNS cd_dep_employed_count")
  //  spark.sql("ANALYZE TABLE customer_demographics COMPUTE STATISTICS FOR COLUMNS cd_dep_college_count")

  spark.sql("ANALYZE TABLE date_dim COMPUTE STATISTICS")
  spark.sql("ANALYZE TABLE date_dim COMPUTE STATISTICS FOR COLUMNS d_date_sk")
  //  spark.sql("ANALYZE TABLE date_dim COMPUTE STATISTICS FOR COLUMNS d_date_id")
  //  spark.sql("ANALYZE TABLE date_dim COMPUTE STATISTICS FOR COLUMNS d_date")
  //  spark.sql("ANALYZE TABLE date_dim COMPUTE STATISTICS FOR COLUMNS d_month_seq")
  //  spark.sql("ANALYZE TABLE date_dim COMPUTE STATISTICS FOR COLUMNS d_week_seq")
  //  spark.sql("ANALYZE TABLE date_dim COMPUTE STATISTICS FOR COLUMNS d_quarter_seq")
  //  spark.sql("ANALYZE TABLE date_dim COMPUTE STATISTICS FOR COLUMNS d_year")
  //  spark.sql("ANALYZE TABLE date_dim COMPUTE STATISTICS FOR COLUMNS d_dow")
  //  spark.sql("ANALYZE TABLE date_dim COMPUTE STATISTICS FOR COLUMNS d_moy")
  //  spark.sql("ANALYZE TABLE date_dim COMPUTE STATISTICS FOR COLUMNS d_dom")
  //  spark.sql("ANALYZE TABLE date_dim COMPUTE STATISTICS FOR COLUMNS d_qoy")
  //  spark.sql("ANALYZE TABLE date_dim COMPUTE STATISTICS FOR COLUMNS d_fy_year")
  //  spark.sql("ANALYZE TABLE date_dim COMPUTE STATISTICS FOR COLUMNS d_fy_quarter_seq")
  //  spark.sql("ANALYZE TABLE date_dim COMPUTE STATISTICS FOR COLUMNS d_fy_week_seq")
  //  spark.sql("ANALYZE TABLE date_dim COMPUTE STATISTICS FOR COLUMNS d_day_name")
  //  spark.sql("ANALYZE TABLE date_dim COMPUTE STATISTICS FOR COLUMNS d_quarter_name")
  //  spark.sql("ANALYZE TABLE date_dim COMPUTE STATISTICS FOR COLUMNS d_holiday")
  //  spark.sql("ANALYZE TABLE date_dim COMPUTE STATISTICS FOR COLUMNS d_weekend")
  //  spark.sql("ANALYZE TABLE date_dim COMPUTE STATISTICS FOR COLUMNS d_following_holiday")
  //  spark.sql("ANALYZE TABLE date_dim COMPUTE STATISTICS FOR COLUMNS d_first_dom")
  //  spark.sql("ANALYZE TABLE date_dim COMPUTE STATISTICS FOR COLUMNS d_last_dom")
  //  spark.sql("ANALYZE TABLE date_dim COMPUTE STATISTICS FOR COLUMNS d_same_day_ly")
  //  spark.sql("ANALYZE TABLE date_dim COMPUTE STATISTICS FOR COLUMNS d_same_day_lq")
  //  spark.sql("ANALYZE TABLE date_dim COMPUTE STATISTICS FOR COLUMNS d_current_day")
  //  spark.sql("ANALYZE TABLE date_dim COMPUTE STATISTICS FOR COLUMNS d_current_week")
  //  spark.sql("ANALYZE TABLE date_dim COMPUTE STATISTICS FOR COLUMNS d_current_month")
  //  spark.sql("ANALYZE TABLE date_dim COMPUTE STATISTICS FOR COLUMNS d_current_quarter")
  //  spark.sql("ANALYZE TABLE date_dim COMPUTE STATISTICS FOR COLUMNS d_current_year")

  //  spark.sql("ANALYZE TABLE warehouse COMPUTE STATISTICS")
  //  spark.sql("ANALYZE TABLE warehouse COMPUTE STATISTICS FOR COLUMNS w_warehouse_sk")
  //  spark.sql("ANALYZE TABLE warehouse COMPUTE STATISTICS FOR COLUMNS w_warehouse_id")
  //  spark.sql("ANALYZE TABLE warehouse COMPUTE STATISTICS FOR COLUMNS w_warehouse_name")
  //  spark.sql("ANALYZE TABLE warehouse COMPUTE STATISTICS FOR COLUMNS w_warehouse_sq_ft")
  //  spark.sql("ANALYZE TABLE warehouse COMPUTE STATISTICS FOR COLUMNS w_street_number")
  //  spark.sql("ANALYZE TABLE warehouse COMPUTE STATISTICS FOR COLUMNS w_street_name")
  //  spark.sql("ANALYZE TABLE warehouse COMPUTE STATISTICS FOR COLUMNS w_street_type")
  //  spark.sql("ANALYZE TABLE warehouse COMPUTE STATISTICS FOR COLUMNS w_suite_number")
  //  spark.sql("ANALYZE TABLE warehouse COMPUTE STATISTICS FOR COLUMNS w_city")
  //  spark.sql("ANALYZE TABLE warehouse COMPUTE STATISTICS FOR COLUMNS w_county")
  //  spark.sql("ANALYZE TABLE warehouse COMPUTE STATISTICS FOR COLUMNS w_state")
  //  spark.sql("ANALYZE TABLE warehouse COMPUTE STATISTICS FOR COLUMNS w_zip")
  //  spark.sql("ANALYZE TABLE warehouse COMPUTE STATISTICS FOR COLUMNS w_country")
  //  spark.sql("ANALYZE TABLE warehouse COMPUTE STATISTICS FOR COLUMNS w_gmt_offset")

  //  spark.sql("ANALYZE TABLE ship_mode COMPUTE STATISTICS")
  //  spark.sql("ANALYZE TABLE ship_mode COMPUTE STATISTICS FOR COLUMNS sm_ship_mode_sk")
  //  spark.sql("ANALYZE TABLE ship_mode COMPUTE STATISTICS FOR COLUMNS sm_ship_mode_id")
  //  spark.sql("ANALYZE TABLE ship_mode COMPUTE STATISTICS FOR COLUMNS sm_type")
  //  spark.sql("ANALYZE TABLE ship_mode COMPUTE STATISTICS FOR COLUMNS sm_code")
  //  spark.sql("ANALYZE TABLE ship_mode COMPUTE STATISTICS FOR COLUMNS sm_carrier")
  //  spark.sql("ANALYZE TABLE ship_mode COMPUTE STATISTICS FOR COLUMNS sm_contract")

  spark.sql("ANALYZE TABLE time_dim COMPUTE STATISTICS")
  spark.sql("ANALYZE TABLE time_dim COMPUTE STATISTICS FOR COLUMNS t_time_sk")
  //  spark.sql("ANALYZE TABLE time_dim COMPUTE STATISTICS FOR COLUMNS t_time_id")
  //  spark.sql("ANALYZE TABLE time_dim COMPUTE STATISTICS FOR COLUMNS t_time")
  //  spark.sql("ANALYZE TABLE time_dim COMPUTE STATISTICS FOR COLUMNS t_hour")
  //  spark.sql("ANALYZE TABLE time_dim COMPUTE STATISTICS FOR COLUMNS t_minute")
  //  spark.sql("ANALYZE TABLE time_dim COMPUTE STATISTICS FOR COLUMNS t_second")
  //  spark.sql("ANALYZE TABLE time_dim COMPUTE STATISTICS FOR COLUMNS t_am_pm")
  //  spark.sql("ANALYZE TABLE time_dim COMPUTE STATISTICS FOR COLUMNS t_shift")
  //  spark.sql("ANALYZE TABLE time_dim COMPUTE STATISTICS FOR COLUMNS t_sub_shift")
  //  spark.sql("ANALYZE TABLE time_dim COMPUTE STATISTICS FOR COLUMNS t_meal_time")

  //  spark.sql("ANALYZE TABLE reason COMPUTE STATISTICS")
  //  spark.sql("ANALYZE TABLE reason COMPUTE STATISTICS FOR COLUMNS r_reason_sk")
  //  spark.sql("ANALYZE TABLE reason COMPUTE STATISTICS FOR COLUMNS r_reason_id")
  //  spark.sql("ANALYZE TABLE reason COMPUTE STATISTICS FOR COLUMNS r_reason_desc")

  //  spark.sql("ANALYZE TABLE income_band COMPUTE STATISTICS")
  //  spark.sql("ANALYZE TABLE income_band COMPUTE STATISTICS FOR COLUMNS ib_income_band_sk")
  //  spark.sql("ANALYZE TABLE income_band COMPUTE STATISTICS FOR COLUMNS ib_lower_bound")
  //  spark.sql("ANALYZE TABLE income_band COMPUTE STATISTICS FOR COLUMNS ib_upper_bound")

  spark.sql("ANALYZE TABLE item COMPUTE STATISTICS")
  spark.sql("ANALYZE TABLE item COMPUTE STATISTICS FOR COLUMNS i_item_sk")
  //  spark.sql("ANALYZE TABLE item COMPUTE STATISTICS FOR COLUMNS i_item_id")
  //  spark.sql("ANALYZE TABLE item COMPUTE STATISTICS FOR COLUMNS i_rec_start_date")
  //  spark.sql("ANALYZE TABLE item COMPUTE STATISTICS FOR COLUMNS i_rec_end_date")
  //  spark.sql("ANALYZE TABLE item COMPUTE STATISTICS FOR COLUMNS i_item_desc")
  //  spark.sql("ANALYZE TABLE item COMPUTE STATISTICS FOR COLUMNS i_current_price")
  //  spark.sql("ANALYZE TABLE item COMPUTE STATISTICS FOR COLUMNS i_wholesale_cost")
  //  spark.sql("ANALYZE TABLE item COMPUTE STATISTICS FOR COLUMNS i_brand_id")
  //  spark.sql("ANALYZE TABLE item COMPUTE STATISTICS FOR COLUMNS i_brand")
  //  spark.sql("ANALYZE TABLE item COMPUTE STATISTICS FOR COLUMNS i_class_id")
  //  spark.sql("ANALYZE TABLE item COMPUTE STATISTICS FOR COLUMNS i_class")
  //  spark.sql("ANALYZE TABLE item COMPUTE STATISTICS FOR COLUMNS i_category_id")
  //  spark.sql("ANALYZE TABLE item COMPUTE STATISTICS FOR COLUMNS i_category")
  //  spark.sql("ANALYZE TABLE item COMPUTE STATISTICS FOR COLUMNS i_manufact_id")
  //  spark.sql("ANALYZE TABLE item COMPUTE STATISTICS FOR COLUMNS i_manufact")
  //  spark.sql("ANALYZE TABLE item COMPUTE STATISTICS FOR COLUMNS i_size")
  //  spark.sql("ANALYZE TABLE item COMPUTE STATISTICS FOR COLUMNS i_formulation")
  //  spark.sql("ANALYZE TABLE item COMPUTE STATISTICS FOR COLUMNS i_color")
  //  spark.sql("ANALYZE TABLE item COMPUTE STATISTICS FOR COLUMNS i_units")
  //  spark.sql("ANALYZE TABLE item COMPUTE STATISTICS FOR COLUMNS i_container")
  //  spark.sql("ANALYZE TABLE item COMPUTE STATISTICS FOR COLUMNS i_manager_id")
  //  spark.sql("ANALYZE TABLE item COMPUTE STATISTICS FOR COLUMNS i_product_name")

  spark.sql("ANALYZE TABLE store COMPUTE STATISTICS")
  spark.sql("ANALYZE TABLE store COMPUTE STATISTICS FOR COLUMNS s_store_sk")
  //  spark.sql("ANALYZE TABLE store COMPUTE STATISTICS FOR COLUMNS s_store_id")
  //  spark.sql("ANALYZE TABLE store COMPUTE STATISTICS FOR COLUMNS s_rec_start_date")
  //  spark.sql("ANALYZE TABLE store COMPUTE STATISTICS FOR COLUMNS s_rec_end_date")
  //  spark.sql("ANALYZE TABLE store COMPUTE STATISTICS FOR COLUMNS s_closed_date_sk")
  //  spark.sql("ANALYZE TABLE store COMPUTE STATISTICS FOR COLUMNS s_store_name")
  //  spark.sql("ANALYZE TABLE store COMPUTE STATISTICS FOR COLUMNS s_number_employees")
  //  spark.sql("ANALYZE TABLE store COMPUTE STATISTICS FOR COLUMNS s_floor_space")
  //  spark.sql("ANALYZE TABLE store COMPUTE STATISTICS FOR COLUMNS s_hours")
  //  spark.sql("ANALYZE TABLE store COMPUTE STATISTICS FOR COLUMNS s_manager")
  //  spark.sql("ANALYZE TABLE store COMPUTE STATISTICS FOR COLUMNS s_market_id")
  //  spark.sql("ANALYZE TABLE store COMPUTE STATISTICS FOR COLUMNS s_geography_class")
  //  spark.sql("ANALYZE TABLE store COMPUTE STATISTICS FOR COLUMNS s_market_desc")
  //  spark.sql("ANALYZE TABLE store COMPUTE STATISTICS FOR COLUMNS s_market_manager")
  //  spark.sql("ANALYZE TABLE store COMPUTE STATISTICS FOR COLUMNS s_division_id")
  //  spark.sql("ANALYZE TABLE store COMPUTE STATISTICS FOR COLUMNS s_division_name")
  //  spark.sql("ANALYZE TABLE store COMPUTE STATISTICS FOR COLUMNS s_company_id")
  //  spark.sql("ANALYZE TABLE store COMPUTE STATISTICS FOR COLUMNS s_company_name")
  //  spark.sql("ANALYZE TABLE store COMPUTE STATISTICS FOR COLUMNS s_street_number")
  //  spark.sql("ANALYZE TABLE store COMPUTE STATISTICS FOR COLUMNS s_street_name")
  //  spark.sql("ANALYZE TABLE store COMPUTE STATISTICS FOR COLUMNS s_street_type")
  //  spark.sql("ANALYZE TABLE store COMPUTE STATISTICS FOR COLUMNS s_suite_number")
  //  spark.sql("ANALYZE TABLE store COMPUTE STATISTICS FOR COLUMNS s_city")
  //  spark.sql("ANALYZE TABLE store COMPUTE STATISTICS FOR COLUMNS s_county")
  //  spark.sql("ANALYZE TABLE store COMPUTE STATISTICS FOR COLUMNS s_state")
  //  spark.sql("ANALYZE TABLE store COMPUTE STATISTICS FOR COLUMNS s_zip")
  //  spark.sql("ANALYZE TABLE store COMPUTE STATISTICS FOR COLUMNS s_country")
  //  spark.sql("ANALYZE TABLE store COMPUTE STATISTICS FOR COLUMNS s_gmt_offset")
  //  spark.sql("ANALYZE TABLE store COMPUTE STATISTICS FOR COLUMNS s_tax_precentage")

  //  spark.sql("ANALYZE TABLE call_center COMPUTE STATISTICS")
  //  spark.sql("ANALYZE TABLE call_center COMPUTE STATISTICS FOR COLUMNS cc_call_center_sk")
  //  spark.sql("ANALYZE TABLE call_center COMPUTE STATISTICS FOR COLUMNS cc_call_center_id")
  //  spark.sql("ANALYZE TABLE call_center COMPUTE STATISTICS FOR COLUMNS cc_rec_start_date")
  //  spark.sql("ANALYZE TABLE call_center COMPUTE STATISTICS FOR COLUMNS cc_rec_end_date")
  //  spark.sql("ANALYZE TABLE call_center COMPUTE STATISTICS FOR COLUMNS cc_closed_date_sk")
  //  spark.sql("ANALYZE TABLE call_center COMPUTE STATISTICS FOR COLUMNS cc_open_date_sk")
  //  spark.sql("ANALYZE TABLE call_center COMPUTE STATISTICS FOR COLUMNS cc_name")
  //  spark.sql("ANALYZE TABLE call_center COMPUTE STATISTICS FOR COLUMNS cc_class")
  //  spark.sql("ANALYZE TABLE call_center COMPUTE STATISTICS FOR COLUMNS cc_employees")
  //  spark.sql("ANALYZE TABLE call_center COMPUTE STATISTICS FOR COLUMNS cc_sq_ft")
  //  spark.sql("ANALYZE TABLE call_center COMPUTE STATISTICS FOR COLUMNS cc_hours")
  //  spark.sql("ANALYZE TABLE call_center COMPUTE STATISTICS FOR COLUMNS cc_manager")
  //  spark.sql("ANALYZE TABLE call_center COMPUTE STATISTICS FOR COLUMNS cc_mkt_id")
  //  spark.sql("ANALYZE TABLE call_center COMPUTE STATISTICS FOR COLUMNS cc_mkt_class")
  //  spark.sql("ANALYZE TABLE call_center COMPUTE STATISTICS FOR COLUMNS cc_mkt_desc")
  //  spark.sql("ANALYZE TABLE call_center COMPUTE STATISTICS FOR COLUMNS cc_market_manager")
  //  spark.sql("ANALYZE TABLE call_center COMPUTE STATISTICS FOR COLUMNS cc_division")
  //  spark.sql("ANALYZE TABLE call_center COMPUTE STATISTICS FOR COLUMNS cc_division_name")
  //  spark.sql("ANALYZE TABLE call_center COMPUTE STATISTICS FOR COLUMNS cc_company")
  //  spark.sql("ANALYZE TABLE call_center COMPUTE STATISTICS FOR COLUMNS cc_company_name")
  //  spark.sql("ANALYZE TABLE call_center COMPUTE STATISTICS FOR COLUMNS cc_street_number")
  //  spark.sql("ANALYZE TABLE call_center COMPUTE STATISTICS FOR COLUMNS cc_street_name")
  //  spark.sql("ANALYZE TABLE call_center COMPUTE STATISTICS FOR COLUMNS cc_street_type")
  //  spark.sql("ANALYZE TABLE call_center COMPUTE STATISTICS FOR COLUMNS cc_suite_number")
  //  spark.sql("ANALYZE TABLE call_center COMPUTE STATISTICS FOR COLUMNS cc_city")
  //  spark.sql("ANALYZE TABLE call_center COMPUTE STATISTICS FOR COLUMNS cc_county")
  //  spark.sql("ANALYZE TABLE call_center COMPUTE STATISTICS FOR COLUMNS cc_state")
  //  spark.sql("ANALYZE TABLE call_center COMPUTE STATISTICS FOR COLUMNS cc_zip")
  //  spark.sql("ANALYZE TABLE call_center COMPUTE STATISTICS FOR COLUMNS cc_country")
  //  spark.sql("ANALYZE TABLE call_center COMPUTE STATISTICS FOR COLUMNS cc_gmt_offset")
  //  spark.sql("ANALYZE TABLE call_center COMPUTE STATISTICS FOR COLUMNS cc_tax_percentage")

  spark.sql("ANALYZE TABLE customer COMPUTE STATISTICS")
  spark.sql("ANALYZE TABLE customer COMPUTE STATISTICS FOR COLUMNS c_customer_sk")
  //  spark.sql("ANALYZE TABLE customer COMPUTE STATISTICS FOR COLUMNS c_customer_id")
  spark.sql("ANALYZE TABLE customer COMPUTE STATISTICS FOR COLUMNS c_current_cdemo_sk")
  //  spark.sql("ANALYZE TABLE customer COMPUTE STATISTICS FOR COLUMNS c_current_hdemo_sk")
  spark.sql("ANALYZE TABLE customer COMPUTE STATISTICS FOR COLUMNS c_current_addr_sk")
  //  spark.sql("ANALYZE TABLE customer COMPUTE STATISTICS FOR COLUMNS c_first_shipto_date_sk")
  //  spark.sql("ANALYZE TABLE customer COMPUTE STATISTICS FOR COLUMNS c_first_sales_date_sk")
  //  spark.sql("ANALYZE TABLE customer COMPUTE STATISTICS FOR COLUMNS c_salutation")
  //  spark.sql("ANALYZE TABLE customer COMPUTE STATISTICS FOR COLUMNS c_first_name")
  //  spark.sql("ANALYZE TABLE customer COMPUTE STATISTICS FOR COLUMNS c_last_name")
  //  spark.sql("ANALYZE TABLE customer COMPUTE STATISTICS FOR COLUMNS c_preferred_cust_flag")
  //  spark.sql("ANALYZE TABLE customer COMPUTE STATISTICS FOR COLUMNS c_birth_day")
  //  spark.sql("ANALYZE TABLE customer COMPUTE STATISTICS FOR COLUMNS c_birth_month")
  //  spark.sql("ANALYZE TABLE customer COMPUTE STATISTICS FOR COLUMNS c_birth_year")
  //  spark.sql("ANALYZE TABLE customer COMPUTE STATISTICS FOR COLUMNS c_birth_country")
  //  spark.sql("ANALYZE TABLE customer COMPUTE STATISTICS FOR COLUMNS c_login")
  //  spark.sql("ANALYZE TABLE customer COMPUTE STATISTICS FOR COLUMNS c_email_address")
  //  spark.sql("ANALYZE TABLE customer COMPUTE STATISTICS FOR COLUMNS c_last_review_date_sk")

  //  spark.sql("ANALYZE TABLE web_site COMPUTE STATISTICS")
  //  spark.sql("ANALYZE TABLE web_site COMPUTE STATISTICS FOR COLUMNS web_site_sk")
  //  spark.sql("ANALYZE TABLE web_site COMPUTE STATISTICS FOR COLUMNS web_site_id")
  //  spark.sql("ANALYZE TABLE web_site COMPUTE STATISTICS FOR COLUMNS web_rec_start_date")
  //  spark.sql("ANALYZE TABLE web_site COMPUTE STATISTICS FOR COLUMNS web_rec_end_date")
  //  spark.sql("ANALYZE TABLE web_site COMPUTE STATISTICS FOR COLUMNS web_name")
  //  spark.sql("ANALYZE TABLE web_site COMPUTE STATISTICS FOR COLUMNS web_open_date_sk")
  //  spark.sql("ANALYZE TABLE web_site COMPUTE STATISTICS FOR COLUMNS web_close_date_sk")
  //  spark.sql("ANALYZE TABLE web_site COMPUTE STATISTICS FOR COLUMNS web_class")
  //  spark.sql("ANALYZE TABLE web_site COMPUTE STATISTICS FOR COLUMNS web_manager")
  //  spark.sql("ANALYZE TABLE web_site COMPUTE STATISTICS FOR COLUMNS web_mkt_id")
  //  spark.sql("ANALYZE TABLE web_site COMPUTE STATISTICS FOR COLUMNS web_mkt_class")
  //  spark.sql("ANALYZE TABLE web_site COMPUTE STATISTICS FOR COLUMNS web_mkt_desc")
  //  spark.sql("ANALYZE TABLE web_site COMPUTE STATISTICS FOR COLUMNS web_market_manager")
  //  spark.sql("ANALYZE TABLE web_site COMPUTE STATISTICS FOR COLUMNS web_company_id")
  //  spark.sql("ANALYZE TABLE web_site COMPUTE STATISTICS FOR COLUMNS web_company_name")
  //  spark.sql("ANALYZE TABLE web_site COMPUTE STATISTICS FOR COLUMNS web_street_number")
  //  spark.sql("ANALYZE TABLE web_site COMPUTE STATISTICS FOR COLUMNS web_street_name")
  //  spark.sql("ANALYZE TABLE web_site COMPUTE STATISTICS FOR COLUMNS web_street_type")
  //  spark.sql("ANALYZE TABLE web_site COMPUTE STATISTICS FOR COLUMNS web_suite_number")
  //  spark.sql("ANALYZE TABLE web_site COMPUTE STATISTICS FOR COLUMNS web_city")
  //  spark.sql("ANALYZE TABLE web_site COMPUTE STATISTICS FOR COLUMNS web_county")
  //  spark.sql("ANALYZE TABLE web_site COMPUTE STATISTICS FOR COLUMNS web_state")
  //  spark.sql("ANALYZE TABLE web_site COMPUTE STATISTICS FOR COLUMNS web_zip")
  //  spark.sql("ANALYZE TABLE web_site COMPUTE STATISTICS FOR COLUMNS web_country")
  //  spark.sql("ANALYZE TABLE web_site COMPUTE STATISTICS FOR COLUMNS web_gmt_offset")
  //  spark.sql("ANALYZE TABLE web_site COMPUTE STATISTICS FOR COLUMNS web_tax_percentage")

  //  spark.sql("ANALYZE TABLE store_returns COMPUTE STATISTICS")
  //  spark.sql("ANALYZE TABLE store_returns COMPUTE STATISTICS FOR COLUMNS sr_returned_date_sk")
  //  spark.sql("ANALYZE TABLE store_returns COMPUTE STATISTICS FOR COLUMNS sr_return_time_sk")
  //  spark.sql("ANALYZE TABLE store_returns COMPUTE STATISTICS FOR COLUMNS sr_item_sk")
  //  spark.sql("ANALYZE TABLE store_returns COMPUTE STATISTICS FOR COLUMNS sr_customer_sk")
  //  spark.sql("ANALYZE TABLE store_returns COMPUTE STATISTICS FOR COLUMNS sr_cdemo_sk")
  //  spark.sql("ANALYZE TABLE store_returns COMPUTE STATISTICS FOR COLUMNS sr_hdemo_sk")
  //  spark.sql("ANALYZE TABLE store_returns COMPUTE STATISTICS FOR COLUMNS sr_addr_sk")
  //  spark.sql("ANALYZE TABLE store_returns COMPUTE STATISTICS FOR COLUMNS sr_store_sk")
  //  spark.sql("ANALYZE TABLE store_returns COMPUTE STATISTICS FOR COLUMNS sr_reason_sk")
  //  spark.sql("ANALYZE TABLE store_returns COMPUTE STATISTICS FOR COLUMNS sr_ticket_number")
  //  spark.sql("ANALYZE TABLE store_returns COMPUTE STATISTICS FOR COLUMNS sr_return_quantity")
  //  spark.sql("ANALYZE TABLE store_returns COMPUTE STATISTICS FOR COLUMNS sr_return_amt")
  //  spark.sql("ANALYZE TABLE store_returns COMPUTE STATISTICS FOR COLUMNS sr_return_tax")
  //  spark.sql("ANALYZE TABLE store_returns COMPUTE STATISTICS FOR COLUMNS sr_return_amt_inc_tax")
  //  spark.sql("ANALYZE TABLE store_returns COMPUTE STATISTICS FOR COLUMNS sr_fee")
  //  spark.sql("ANALYZE TABLE store_returns COMPUTE STATISTICS FOR COLUMNS sr_return_ship_cost")
  //  spark.sql("ANALYZE TABLE store_returns COMPUTE STATISTICS FOR COLUMNS sr_refunded_cash")
  //  spark.sql("ANALYZE TABLE store_returns COMPUTE STATISTICS FOR COLUMNS sr_reversed_charge")
  //  spark.sql("ANALYZE TABLE store_returns COMPUTE STATISTICS FOR COLUMNS sr_store_credit")
  //  spark.sql("ANALYZE TABLE store_returns COMPUTE STATISTICS FOR COLUMNS sr_net_loss")

  spark.sql("ANALYZE TABLE household_demographics COMPUTE STATISTICS")
  spark.sql("ANALYZE TABLE household_demographics COMPUTE STATISTICS FOR COLUMNS hd_demo_sk")
  //  spark.sql("ANALYZE TABLE household_demographics COMPUTE STATISTICS FOR COLUMNS hd_income_band_sk")
  //  spark.sql("ANALYZE TABLE household_demographics COMPUTE STATISTICS FOR COLUMNS hd_buy_potential")
  //  spark.sql("ANALYZE TABLE household_demographics COMPUTE STATISTICS FOR COLUMNS hd_dep_count")
  //  spark.sql("ANALYZE TABLE household_demographics COMPUTE STATISTICS FOR COLUMNS hd_vehicle_count")

  //  spark.sql("ANALYZE TABLE web_page COMPUTE STATISTICS")
  //  spark.sql("ANALYZE TABLE web_page COMPUTE STATISTICS FOR COLUMNS wp_web_page_sk")
  //  spark.sql("ANALYZE TABLE web_page COMPUTE STATISTICS FOR COLUMNS wp_web_page_id")
  //  spark.sql("ANALYZE TABLE web_page COMPUTE STATISTICS FOR COLUMNS wp_rec_start_date")
  //  spark.sql("ANALYZE TABLE web_page COMPUTE STATISTICS FOR COLUMNS wp_rec_end_date")
  //  spark.sql("ANALYZE TABLE web_page COMPUTE STATISTICS FOR COLUMNS wp_creation_date_sk")
  //  spark.sql("ANALYZE TABLE web_page COMPUTE STATISTICS FOR COLUMNS wp_access_date_sk")
  //  spark.sql("ANALYZE TABLE web_page COMPUTE STATISTICS FOR COLUMNS wp_autogen_flag")
  //  spark.sql("ANALYZE TABLE web_page COMPUTE STATISTICS FOR COLUMNS wp_customer_sk")
  //  spark.sql("ANALYZE TABLE web_page COMPUTE STATISTICS FOR COLUMNS wp_url")
  //  spark.sql("ANALYZE TABLE web_page COMPUTE STATISTICS FOR COLUMNS wp_type")
  //  spark.sql("ANALYZE TABLE web_page COMPUTE STATISTICS FOR COLUMNS wp_char_count")
  //  spark.sql("ANALYZE TABLE web_page COMPUTE STATISTICS FOR COLUMNS wp_link_count")
  //  spark.sql("ANALYZE TABLE web_page COMPUTE STATISTICS FOR COLUMNS wp_image_count")
  //  spark.sql("ANALYZE TABLE web_page COMPUTE STATISTICS FOR COLUMNS wp_max_ad_count")

  //  spark.sql("ANALYZE TABLE promotion COMPUTE STATISTICS")
  //  spark.sql("ANALYZE TABLE promotion COMPUTE STATISTICS FOR COLUMNS p_promo_sk")
  //  spark.sql("ANALYZE TABLE promotion COMPUTE STATISTICS FOR COLUMNS p_promo_id")
  //  spark.sql("ANALYZE TABLE promotion COMPUTE STATISTICS FOR COLUMNS p_start_date_sk")
  //  spark.sql("ANALYZE TABLE promotion COMPUTE STATISTICS FOR COLUMNS p_end_date_sk")
  //  spark.sql("ANALYZE TABLE promotion COMPUTE STATISTICS FOR COLUMNS p_item_sk")
  //  spark.sql("ANALYZE TABLE promotion COMPUTE STATISTICS FOR COLUMNS p_cost")
  //  spark.sql("ANALYZE TABLE promotion COMPUTE STATISTICS FOR COLUMNS p_response_target")
  //  spark.sql("ANALYZE TABLE promotion COMPUTE STATISTICS FOR COLUMNS p_promo_name")
  //  spark.sql("ANALYZE TABLE promotion COMPUTE STATISTICS FOR COLUMNS p_channel_dmail")
  //  spark.sql("ANALYZE TABLE promotion COMPUTE STATISTICS FOR COLUMNS p_channel_email")
  //  spark.sql("ANALYZE TABLE promotion COMPUTE STATISTICS FOR COLUMNS p_channel_catalog")
  //  spark.sql("ANALYZE TABLE promotion COMPUTE STATISTICS FOR COLUMNS p_channel_tv")
  //  spark.sql("ANALYZE TABLE promotion COMPUTE STATISTICS FOR COLUMNS p_channel_radio")
  //  spark.sql("ANALYZE TABLE promotion COMPUTE STATISTICS FOR COLUMNS p_channel_press")
  //  spark.sql("ANALYZE TABLE promotion COMPUTE STATISTICS FOR COLUMNS p_channel_event")
  //  spark.sql("ANALYZE TABLE promotion COMPUTE STATISTICS FOR COLUMNS p_channel_demo")
  //  spark.sql("ANALYZE TABLE promotion COMPUTE STATISTICS FOR COLUMNS p_channel_details")
  //  spark.sql("ANALYZE TABLE promotion COMPUTE STATISTICS FOR COLUMNS p_purpose")
  //  spark.sql("ANALYZE TABLE promotion COMPUTE STATISTICS FOR COLUMNS p_discount_active")

  //  spark.sql("ANALYZE TABLE catalog_page COMPUTE STATISTICS")
  //  spark.sql("ANALYZE TABLE catalog_page COMPUTE STATISTICS FOR COLUMNS cp_catalog_page_sk")
  //  spark.sql("ANALYZE TABLE catalog_page COMPUTE STATISTICS FOR COLUMNS cp_catalog_page_id")
  //  spark.sql("ANALYZE TABLE catalog_page COMPUTE STATISTICS FOR COLUMNS cp_start_date_sk")
  //  spark.sql("ANALYZE TABLE catalog_page COMPUTE STATISTICS FOR COLUMNS cp_end_date_sk")
  //  spark.sql("ANALYZE TABLE catalog_page COMPUTE STATISTICS FOR COLUMNS cp_department")
  //  spark.sql("ANALYZE TABLE catalog_page COMPUTE STATISTICS FOR COLUMNS cp_catalog_number")
  //  spark.sql("ANALYZE TABLE catalog_page COMPUTE STATISTICS FOR COLUMNS cp_catalog_page_number")
  //  spark.sql("ANALYZE TABLE catalog_page COMPUTE STATISTICS FOR COLUMNS cp_description")
  //  spark.sql("ANALYZE TABLE catalog_page COMPUTE STATISTICS FOR COLUMNS cp_type")

  //  spark.sql("ANALYZE TABLE inventory COMPUTE STATISTICS")
  //  spark.sql("ANALYZE TABLE inventory COMPUTE STATISTICS FOR COLUMNS inv_date_sk")
  //  spark.sql("ANALYZE TABLE inventory COMPUTE STATISTICS FOR COLUMNS inv_item_sk")
  //  spark.sql("ANALYZE TABLE inventory COMPUTE STATISTICS FOR COLUMNS inv_warehouse_sk")
  //  spark.sql("ANALYZE TABLE inventory COMPUTE STATISTICS FOR COLUMNS inv_quantity_on_hand")

  //  spark.sql("ANALYZE TABLE catalog_returns COMPUTE STATISTICS")
  //  spark.sql("ANALYZE TABLE catalog_returns COMPUTE STATISTICS FOR COLUMNS cr_returned_date_sk")
  //  spark.sql("ANALYZE TABLE catalog_returns COMPUTE STATISTICS FOR COLUMNS cr_returned_time_sk")
  //  spark.sql("ANALYZE TABLE catalog_returns COMPUTE STATISTICS FOR COLUMNS cr_item_sk")
  //  spark.sql("ANALYZE TABLE catalog_returns COMPUTE STATISTICS FOR COLUMNS cr_refunded_customer_sk")
  //  spark.sql("ANALYZE TABLE catalog_returns COMPUTE STATISTICS FOR COLUMNS cr_refunded_cdemo_sk")
  //  spark.sql("ANALYZE TABLE catalog_returns COMPUTE STATISTICS FOR COLUMNS cr_refunded_hdemo_sk")
  //  spark.sql("ANALYZE TABLE catalog_returns COMPUTE STATISTICS FOR COLUMNS cr_refunded_addr_sk")
  //  spark.sql("ANALYZE TABLE catalog_returns COMPUTE STATISTICS FOR COLUMNS cr_returning_customer_sk")
  //  spark.sql("ANALYZE TABLE catalog_returns COMPUTE STATISTICS FOR COLUMNS cr_returning_cdemo_sk")
  //  spark.sql("ANALYZE TABLE catalog_returns COMPUTE STATISTICS FOR COLUMNS cr_returning_hdemo_sk")
  //  spark.sql("ANALYZE TABLE catalog_returns COMPUTE STATISTICS FOR COLUMNS cr_returning_addr_sk")
  //  spark.sql("ANALYZE TABLE catalog_returns COMPUTE STATISTICS FOR COLUMNS cr_call_center_sk")
  //  spark.sql("ANALYZE TABLE catalog_returns COMPUTE STATISTICS FOR COLUMNS cr_catalog_page_sk")
  //  spark.sql("ANALYZE TABLE catalog_returns COMPUTE STATISTICS FOR COLUMNS cr_ship_mode_sk")
  //  spark.sql("ANALYZE TABLE catalog_returns COMPUTE STATISTICS FOR COLUMNS cr_warehouse_sk")
  //  spark.sql("ANALYZE TABLE catalog_returns COMPUTE STATISTICS FOR COLUMNS cr_reason_sk")
  //  spark.sql("ANALYZE TABLE catalog_returns COMPUTE STATISTICS FOR COLUMNS cr_order_number")
  //  spark.sql("ANALYZE TABLE catalog_returns COMPUTE STATISTICS FOR COLUMNS cr_return_quantity")
  //  spark.sql("ANALYZE TABLE catalog_returns COMPUTE STATISTICS FOR COLUMNS cr_return_amount")
  //  spark.sql("ANALYZE TABLE catalog_returns COMPUTE STATISTICS FOR COLUMNS cr_return_tax")
  //  spark.sql("ANALYZE TABLE catalog_returns COMPUTE STATISTICS FOR COLUMNS cr_return_amt_inc_tax")
  //  spark.sql("ANALYZE TABLE catalog_returns COMPUTE STATISTICS FOR COLUMNS cr_fee")
  //  spark.sql("ANALYZE TABLE catalog_returns COMPUTE STATISTICS FOR COLUMNS cr_return_ship_cost")
  //  spark.sql("ANALYZE TABLE catalog_returns COMPUTE STATISTICS FOR COLUMNS cr_refunded_cash")
  //  spark.sql("ANALYZE TABLE catalog_returns COMPUTE STATISTICS FOR COLUMNS cr_reversed_charge")
  //  spark.sql("ANALYZE TABLE catalog_returns COMPUTE STATISTICS FOR COLUMNS cr_store_credit")
  //  spark.sql("ANALYZE TABLE catalog_returns COMPUTE STATISTICS FOR COLUMNS cr_net_loss")

  //  spark.sql("ANALYZE TABLE web_returns COMPUTE STATISTICS")
  //  spark.sql("ANALYZE TABLE web_returns COMPUTE STATISTICS FOR COLUMNS wr_returned_date_sk")
  //  spark.sql("ANALYZE TABLE web_returns COMPUTE STATISTICS FOR COLUMNS wr_returned_time_sk")
  //  spark.sql("ANALYZE TABLE web_returns COMPUTE STATISTICS FOR COLUMNS wr_item_sk")
  //  spark.sql("ANALYZE TABLE web_returns COMPUTE STATISTICS FOR COLUMNS wr_refunded_customer_sk")
  //  spark.sql("ANALYZE TABLE web_returns COMPUTE STATISTICS FOR COLUMNS wr_refunded_cdemo_sk")
  //  spark.sql("ANALYZE TABLE web_returns COMPUTE STATISTICS FOR COLUMNS wr_refunded_hdemo_sk")
  //  spark.sql("ANALYZE TABLE web_returns COMPUTE STATISTICS FOR COLUMNS wr_refunded_addr_sk")
  //  spark.sql("ANALYZE TABLE web_returns COMPUTE STATISTICS FOR COLUMNS wr_returning_customer_sk")
  //  spark.sql("ANALYZE TABLE web_returns COMPUTE STATISTICS FOR COLUMNS wr_returning_cdemo_sk")
  //  spark.sql("ANALYZE TABLE web_returns COMPUTE STATISTICS FOR COLUMNS wr_returning_hdemo_sk")
  //  spark.sql("ANALYZE TABLE web_returns COMPUTE STATISTICS FOR COLUMNS wr_returning_addr_sk")
  //  spark.sql("ANALYZE TABLE web_returns COMPUTE STATISTICS FOR COLUMNS wr_web_page_sk")
  //  spark.sql("ANALYZE TABLE web_returns COMPUTE STATISTICS FOR COLUMNS wr_reason_sk")
  //  spark.sql("ANALYZE TABLE web_returns COMPUTE STATISTICS FOR COLUMNS wr_order_number")
  //  spark.sql("ANALYZE TABLE web_returns COMPUTE STATISTICS FOR COLUMNS wr_return_quantity")
  //  spark.sql("ANALYZE TABLE web_returns COMPUTE STATISTICS FOR COLUMNS wr_return_amt")
  //  spark.sql("ANALYZE TABLE web_returns COMPUTE STATISTICS FOR COLUMNS wr_return_tax")
  //  spark.sql("ANALYZE TABLE web_returns COMPUTE STATISTICS FOR COLUMNS wr_return_amt_inc_tax")
  //  spark.sql("ANALYZE TABLE web_returns COMPUTE STATISTICS FOR COLUMNS wr_fee")
  //  spark.sql("ANALYZE TABLE web_returns COMPUTE STATISTICS FOR COLUMNS wr_return_ship_cost")
  //  spark.sql("ANALYZE TABLE web_returns COMPUTE STATISTICS FOR COLUMNS wr_refunded_cash")
  //  spark.sql("ANALYZE TABLE web_returns COMPUTE STATISTICS FOR COLUMNS wr_reversed_charge")
  //  spark.sql("ANALYZE TABLE web_returns COMPUTE STATISTICS FOR COLUMNS wr_account_credit")
  //  spark.sql("ANALYZE TABLE web_returns COMPUTE STATISTICS FOR COLUMNS wr_net_loss")

  spark.sql("ANALYZE TABLE web_sales COMPUTE STATISTICS")
  spark.sql("ANALYZE TABLE web_sales COMPUTE STATISTICS FOR COLUMNS ws_sold_date_sk")
  //  spark.sql("ANALYZE TABLE web_sales COMPUTE STATISTICS FOR COLUMNS ws_sold_time_sk")
  //  spark.sql("ANALYZE TABLE web_sales COMPUTE STATISTICS FOR COLUMNS ws_ship_date_sk")
  //  spark.sql("ANALYZE TABLE web_sales COMPUTE STATISTICS FOR COLUMNS ws_item_sk")
  spark.sql("ANALYZE TABLE web_sales COMPUTE STATISTICS FOR COLUMNS ws_bill_customer_sk")
  //  spark.sql("ANALYZE TABLE web_sales COMPUTE STATISTICS FOR COLUMNS ws_bill_cdemo_sk")
  //  spark.sql("ANALYZE TABLE web_sales COMPUTE STATISTICS FOR COLUMNS ws_bill_hdemo_sk")
  //  spark.sql("ANALYZE TABLE web_sales COMPUTE STATISTICS FOR COLUMNS ws_bill_addr_sk")
  //  spark.sql("ANALYZE TABLE web_sales COMPUTE STATISTICS FOR COLUMNS ws_ship_customer_sk")
  //  spark.sql("ANALYZE TABLE web_sales COMPUTE STATISTICS FOR COLUMNS ws_ship_cdemo_sk")
  //  spark.sql("ANALYZE TABLE web_sales COMPUTE STATISTICS FOR COLUMNS ws_ship_hdemo_sk")
  //  spark.sql("ANALYZE TABLE web_sales COMPUTE STATISTICS FOR COLUMNS ws_ship_addr_sk")
  //  spark.sql("ANALYZE TABLE web_sales COMPUTE STATISTICS FOR COLUMNS ws_web_page_sk")
  //  spark.sql("ANALYZE TABLE web_sales COMPUTE STATISTICS FOR COLUMNS ws_web_site_sk")
  //  spark.sql("ANALYZE TABLE web_sales COMPUTE STATISTICS FOR COLUMNS ws_ship_mode_sk")
  //  spark.sql("ANALYZE TABLE web_sales COMPUTE STATISTICS FOR COLUMNS ws_warehouse_sk")
  //  spark.sql("ANALYZE TABLE web_sales COMPUTE STATISTICS FOR COLUMNS ws_promo_sk")
  //  spark.sql("ANALYZE TABLE web_sales COMPUTE STATISTICS FOR COLUMNS ws_order_number")
  //  spark.sql("ANALYZE TABLE web_sales COMPUTE STATISTICS FOR COLUMNS ws_quantity")
  //  spark.sql("ANALYZE TABLE web_sales COMPUTE STATISTICS FOR COLUMNS ws_wholesale_cost")
  //  spark.sql("ANALYZE TABLE web_sales COMPUTE STATISTICS FOR COLUMNS ws_list_price")
  //  spark.sql("ANALYZE TABLE web_sales COMPUTE STATISTICS FOR COLUMNS ws_sales_price")
  //  spark.sql("ANALYZE TABLE web_sales COMPUTE STATISTICS FOR COLUMNS ws_ext_discount_amt")
  //  spark.sql("ANALYZE TABLE web_sales COMPUTE STATISTICS FOR COLUMNS ws_ext_sales_price")
  //  spark.sql("ANALYZE TABLE web_sales COMPUTE STATISTICS FOR COLUMNS ws_ext_wholesale_cost")
  //  spark.sql("ANALYZE TABLE web_sales COMPUTE STATISTICS FOR COLUMNS ws_ext_list_price")
  //  spark.sql("ANALYZE TABLE web_sales COMPUTE STATISTICS FOR COLUMNS ws_ext_tax")
  //  spark.sql("ANALYZE TABLE web_sales COMPUTE STATISTICS FOR COLUMNS ws_coupon_amt")
  //  spark.sql("ANALYZE TABLE web_sales COMPUTE STATISTICS FOR COLUMNS ws_ext_ship_cost")
  //  spark.sql("ANALYZE TABLE web_sales COMPUTE STATISTICS FOR COLUMNS ws_net_paid")
  //  spark.sql("ANALYZE TABLE web_sales COMPUTE STATISTICS FOR COLUMNS ws_net_paid_inc_tax")
  //  spark.sql("ANALYZE TABLE web_sales COMPUTE STATISTICS FOR COLUMNS ws_net_paid_inc_ship")
  //  spark.sql("ANALYZE TABLE web_sales COMPUTE STATISTICS FOR COLUMNS ws_net_paid_inc_ship_tax")
  //  spark.sql("ANALYZE TABLE web_sales COMPUTE STATISTICS FOR COLUMNS ws_net_profit")

  spark.sql("ANALYZE TABLE catalog_sales COMPUTE STATISTICS")
  spark.sql("ANALYZE TABLE catalog_sales COMPUTE STATISTICS FOR COLUMNS cs_sold_date_sk")
  //  spark.sql("ANALYZE TABLE catalog_sales COMPUTE STATISTICS FOR COLUMNS cs_sold_time_sk")
  //  spark.sql("ANALYZE TABLE catalog_sales COMPUTE STATISTICS FOR COLUMNS cs_ship_date_sk")
  //  spark.sql("ANALYZE TABLE catalog_sales COMPUTE STATISTICS FOR COLUMNS cs_bill_customer_sk")
  //  spark.sql("ANALYZE TABLE catalog_sales COMPUTE STATISTICS FOR COLUMNS cs_bill_cdemo_sk")
  //  spark.sql("ANALYZE TABLE catalog_sales COMPUTE STATISTICS FOR COLUMNS cs_bill_hdemo_sk")
  //  spark.sql("ANALYZE TABLE catalog_sales COMPUTE STATISTICS FOR COLUMNS cs_bill_addr_sk")
  spark.sql("ANALYZE TABLE catalog_sales COMPUTE STATISTICS FOR COLUMNS cs_ship_customer_sk")
  //  spark.sql("ANALYZE TABLE catalog_sales COMPUTE STATISTICS FOR COLUMNS cs_ship_cdemo_sk")
  //  spark.sql("ANALYZE TABLE catalog_sales COMPUTE STATISTICS FOR COLUMNS cs_ship_hdemo_sk")
  //  spark.sql("ANALYZE TABLE catalog_sales COMPUTE STATISTICS FOR COLUMNS cs_ship_addr_sk")
  //  spark.sql("ANALYZE TABLE catalog_sales COMPUTE STATISTICS FOR COLUMNS cs_call_center_sk")
  //  spark.sql("ANALYZE TABLE catalog_sales COMPUTE STATISTICS FOR COLUMNS cs_catalog_page_sk")
  //  spark.sql("ANALYZE TABLE catalog_sales COMPUTE STATISTICS FOR COLUMNS cs_ship_mode_sk")
  //  spark.sql("ANALYZE TABLE catalog_sales COMPUTE STATISTICS FOR COLUMNS cs_warehouse_sk")
  //  spark.sql("ANALYZE TABLE catalog_sales COMPUTE STATISTICS FOR COLUMNS cs_item_sk")
  //  spark.sql("ANALYZE TABLE catalog_sales COMPUTE STATISTICS FOR COLUMNS cs_promo_sk")
  //  spark.sql("ANALYZE TABLE catalog_sales COMPUTE STATISTICS FOR COLUMNS cs_order_number")
  //  spark.sql("ANALYZE TABLE catalog_sales COMPUTE STATISTICS FOR COLUMNS cs_quantity")
  //  spark.sql("ANALYZE TABLE catalog_sales COMPUTE STATISTICS FOR COLUMNS cs_wholesale_cost")
  //  spark.sql("ANALYZE TABLE catalog_sales COMPUTE STATISTICS FOR COLUMNS cs_list_price")
  //  spark.sql("ANALYZE TABLE catalog_sales COMPUTE STATISTICS FOR COLUMNS cs_sales_price")
  //  spark.sql("ANALYZE TABLE catalog_sales COMPUTE STATISTICS FOR COLUMNS cs_ext_discount_amt")
  //  spark.sql("ANALYZE TABLE catalog_sales COMPUTE STATISTICS FOR COLUMNS cs_ext_sales_price")
  //  spark.sql("ANALYZE TABLE catalog_sales COMPUTE STATISTICS FOR COLUMNS cs_ext_wholesale_cost")
  //  spark.sql("ANALYZE TABLE catalog_sales COMPUTE STATISTICS FOR COLUMNS cs_ext_list_price")
  //  spark.sql("ANALYZE TABLE catalog_sales COMPUTE STATISTICS FOR COLUMNS cs_ext_tax")
  //  spark.sql("ANALYZE TABLE catalog_sales COMPUTE STATISTICS FOR COLUMNS cs_coupon_amt")
  //  spark.sql("ANALYZE TABLE catalog_sales COMPUTE STATISTICS FOR COLUMNS cs_ext_ship_cost")
  //  spark.sql("ANALYZE TABLE catalog_sales COMPUTE STATISTICS FOR COLUMNS cs_net_paid")
  //  spark.sql("ANALYZE TABLE catalog_sales COMPUTE STATISTICS FOR COLUMNS cs_net_paid_inc_tax")
  //  spark.sql("ANALYZE TABLE catalog_sales COMPUTE STATISTICS FOR COLUMNS cs_net_paid_inc_ship")
  //  spark.sql("ANALYZE TABLE catalog_sales COMPUTE STATISTICS FOR COLUMNS cs_net_paid_inc_ship_tax")
  //  spark.sql("ANALYZE TABLE catalog_sales COMPUTE STATISTICS FOR COLUMNS cs_net_profit")

  spark.sql("ANALYZE TABLE store_sales COMPUTE STATISTICS")
  spark.sql("ANALYZE TABLE store_sales COMPUTE STATISTICS FOR COLUMNS ss_sold_date_sk")
  spark.sql("ANALYZE TABLE store_sales COMPUTE STATISTICS FOR COLUMNS ss_sold_time_sk")
  spark.sql("ANALYZE TABLE store_sales COMPUTE STATISTICS FOR COLUMNS ss_item_sk")
  spark.sql("ANALYZE TABLE store_sales COMPUTE STATISTICS FOR COLUMNS ss_customer_sk")
  //  spark.sql("ANALYZE TABLE store_sales COMPUTE STATISTICS FOR COLUMNS ss_cdemo_sk")
  spark.sql("ANALYZE TABLE store_sales COMPUTE STATISTICS FOR COLUMNS ss_hdemo_sk")
  //  spark.sql("ANALYZE TABLE store_sales COMPUTE STATISTICS FOR COLUMNS ss_addr_sk")
  spark.sql("ANALYZE TABLE store_sales COMPUTE STATISTICS FOR COLUMNS ss_store_sk")
  //  spark.sql("ANALYZE TABLE store_sales COMPUTE STATISTICS FOR COLUMNS ss_promo_sk")
  //  spark.sql("ANALYZE TABLE store_sales COMPUTE STATISTICS FOR COLUMNS ss_ticket_number")
  //  spark.sql("ANALYZE TABLE store_sales COMPUTE STATISTICS FOR COLUMNS ss_quantity")
  //  spark.sql("ANALYZE TABLE store_sales COMPUTE STATISTICS FOR COLUMNS ss_wholesale_cost")
  //  spark.sql("ANALYZE TABLE store_sales COMPUTE STATISTICS FOR COLUMNS ss_list_price")
  //  spark.sql("ANALYZE TABLE store_sales COMPUTE STATISTICS FOR COLUMNS ss_sales_price")
  //  spark.sql("ANALYZE TABLE store_sales COMPUTE STATISTICS FOR COLUMNS ss_ext_discount_amt")
  //  spark.sql("ANALYZE TABLE store_sales COMPUTE STATISTICS FOR COLUMNS ss_ext_sales_price")
  //  spark.sql("ANALYZE TABLE store_sales COMPUTE STATISTICS FOR COLUMNS ss_ext_wholesale_cost")
  //  spark.sql("ANALYZE TABLE store_sales COMPUTE STATISTICS FOR COLUMNS ss_ext_list_price")
  //  spark.sql("ANALYZE TABLE store_sales COMPUTE STATISTICS FOR COLUMNS ss_ext_tax")
  //  spark.sql("ANALYZE TABLE store_sales COMPUTE STATISTICS FOR COLUMNS ss_coupon_amt")
  //  spark.sql("ANALYZE TABLE store_sales COMPUTE STATISTICS FOR COLUMNS ss_net_paid")
  //  spark.sql("ANALYZE TABLE store_sales COMPUTE STATISTICS FOR COLUMNS ss_net_paid_inc_tax")
  //  spark.sql("ANALYZE TABLE store_sales COMPUTE STATISTICS FOR COLUMNS ss_net_profit")


  val time4 = System.currentTimeMillis()


  val writeTableTime = time2 - time1
  val allTableCountTime = time3 -time2
  val analyzeNotAllColTime = time4 - time3


}
